[package]
name = "async-fuse"
version = "0.2.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/async-fuse"
homepage = "https://github.com/udoprog/async-fuse"
documentation = "https://docs.rs/async-fuse"
description = """
Container to simplify the fusing of futures.
"""

[dev-dependencies]
tokio = { version = "1.0.0", features = ["full"] }
