[package]
name = "futures-option"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = "0.3.0-alpha.17"

[dev-dependencies]
futures-preview = {version = "0.3.0-alpha.17", features = ["nightly", "async-await"]}