[package]
name = "async-fuse"
version = "0.3.3"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["futures", "async", "future"]
categories = ["asynchronous"]
repository = "https://github.com/udoprog/async-fuse"
homepage = "https://github.com/udoprog/async-fuse"
documentation = "https://docs.rs/async-fuse"
description = """
Helpers for fusing asynchronous computations.
"""

[dependencies]
pin-project-lite = "0.2.0"

[dev-dependencies]
tokio = { version = "1.0.0", features = ["full"] }
