[package]
name = "futures-option"
version = "0.2.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/futures-option"
homepage = "https://github.com/udoprog/futures-option"
documentation = "https://docs.rs/futures-option"
description = """
Extension traits for dealing with optional futures and streams
"""

[dependencies]
futures-core = "0.3.1"

[dev-dependencies]
futures = {version = "0.3.1" }