[package]
name = "async-fuse"
version = "0.11.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["futures", "async", "future"]
categories = ["asynchronous"]
repository = "https://github.com/udoprog/async-fuse"
homepage = "https://github.com/udoprog/async-fuse"
documentation = "https://docs.rs/async-fuse"
description = """
Helpers for fusing asynchronous computations.
"""

[features]
stream = ["futures-core"]

[dependencies]
futures-core = { version = "0.3.8", optional = true }

[dev-dependencies]
async-stream = "0.3.0"
tokio = { version = "1.0.0", features = ["full"] }

[package.metadata.docs.rs]
all-features = true
